---
#开发环境
spring:
  config:
    activate:
      on-profile: dev
pdf-server:
  server-url: http://192.168.1.60:10004/pdf
  app-code: hep
  view-url: http://192.168.1.60:1801/report_view/group/
---
#测试环境
spring:
  config:
    activate:
      on-profile: sit
pdf-server:
  server-url: http://192.168.1.60:10004/pdf
  app-code: hep
  view-url: http://192.168.1.60:1801/report_view/group/
---
#预发布环境
spring:
  config:
    activate:
      on-profile: uat
pdf-server:
  server-url: http://192.168.1.60:10004/pdf
  app-code: hep
  view-url: http://192.168.1.60:1801/report_view/group/
---
#产品环境
spring:
  config:
    activate:
      on-profile: prd
pdf-server:
  server-url: http://192.168.1.60:10004/pdf
  app-code: hep
  view-url: http://192.168.1.60:1801/report_view/group/