---
#本地测试环境
spring:
  config:
    activate:
      on-profile: lte

---
#开发环境
spring:
  config:
    activate:
      on-profile: dev
elasticjob:
  reg-center:
    server-lists: 192.168.1.60:2181
    namespace: dev-dows-hep
---
#测试环境
spring:
  config:
    activate:
      on-profile: sit
elasticjob:
  reg-center:
    server-lists: 192.168.1.60:2281
    namespace: test-dows-hep
---
#预发布环境
spring:
  config:
    activate:
      on-profile: uat
elasticjob:
  reg-center:
    server-lists: 192.168.1.60:2381
    namespace: staging-dows-hep


---
#预发布环境
spring:
  config:
    activate:
      on-profile: prd
elasticjob:
  reg-center:
    server-lists: 192.168.1.60:2381
    namespace: staging-dows-hep
