
---
#生产环境
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      #uri: mongodb://192.168.1.60:17017
      username: mongo
      password: "123456"
      database: hep
      port: 17017
      host: 192.168.1.60
      #collection-name: user
      #authentication-database: user



---
#测试环境
spring:
  config:
    activate:
      on-profile: sit
  data:
    mongodb:
      #uri: mongodb://192.168.1.60:17017
      username: mongo
      password: "123456"
      database: hep
      port: 17017
      host: 192.168.1.60
      #collection-name: user
      #authentication-database: user

---
#开发环境
spring:
  config:
    activate:
      on-profile: uat
  data:
    mongodb:
      #uri: mongodb://192.168.1.60:17017
      username: mongo
      password: "123456"
      database: hep
      port: 17017
      host: 192.168.1.60
      #collection-name: user
      #authentication-database: hep
---
#本地环境
spring:
  config:
    activate:
      on-profile: prd
  data:
    mongodb:
      #uri: mongodb://192.168.1.60:17017
      username: mongo
      password: "123456"
      database: hep
      port: 17017
      host: 192.168.1.60
      #collection-name: user
      #authentication-database: hep