version: '3'
services:
  api-hep-admin-lte:
    image: registry.cn-hangzhou.aliyuncs.com/findsoft/api-hep-admin-lte:$TAG
    restart: on-failure:3
    container_name: api-hep-admin-lte
    environment:
      - TZ=$TZ
      - JVM_OPTS=-server -Xms1024m -Xmx1024m
      - JAVA_OPTS=-Djasypt.encryptor.password=02700083-9fd9-4b82-a4b4-9177e0560e92 -Dspring.config.location=/dows/saas/hep-admin/configs/ -Dspring.profiles.active=lte
      #- APM=-javaagent:/dows/paas/apm/skywalking-agent/skywalking-agent.jar -Dskywalking.agent.service_name=hep-admin-dev -Dskywalking.collector.backend_service=192.168.1.60:11800
    ports:
      - 8080:8080
      - 80:80
      - 5005:5005
    volumes:
      - ./logs:/dows/saas/hep-admin/logs
      - ./configs:/dows/saas/hep-admin/configs
      - ./resources:/data/resources/images/hep
      #- /dows/paas/apm/skywalking-agent-8.16.0:/dows/paas/apm/skywalking-agent
    networks:
      - sit_net
#    networks:
#      dev_net:
#        ipv4_address: 172.18.0.6

networks:
  sit_net:
    external: true
