indicator:
  - name: ddd
    mix: -30
    max: 90
    factor: 0.3
    weights:
      -90: 1.1
      -80: 1.2
      -70: 1.3
      -60: 1.4

  - name: ccc
    mix: -60
    max: 60
    factor: 0.9
    #权重
    weights:
      -90: 1.1
      -80: 1.2
      -70: 1.3
      -60: 1.4

  - name: bbb
    mix: -70
    max: 90
    factor: 0.99
    weights:
      -90: 1.1
      -80: 1.2
      -70: 1.3
      -60: 1.4


score-settings:

  hp-score-min: 30
  hp-score-max: 100

  money-score-min: 0
  money-score-max: 100

  judge-score-min: 30
  judge-score-max: 100
