---
#开发环境
spring:
  config:
    activate:
      on-profile: dev
pdf-server:
  url: http://192.168.1.60:10004/pdf
  namespace: dev-dows-hep
---
#测试环境
spring:
  config:
    activate:
      on-profile: sit
pdf-server:
  url: http://192.168.1.60:10004/pdf
  namespace: sit-dows-hep
---
#预发布环境
spring:
  config:
    activate:
      on-profile: uat
pdf-server:
  url: http://192.168.1.60:10004/pdf
  namespace: uat-dows-hep
---
#产品环境
spring:
  config:
    activate:
      on-profile: prd
pdf-server:
  url: http://192.168.1.60:10004/pdf
  namespace: prd-dows-hep