dows:
  websocket:
    port: 1111
    producer:
      retry:
        cron: 0/3 * * * * ?
        duration: 3

---
#测试环境
spring:
  config:
    activate:
      on-profile: dev
springdoc:
  api-docs:
    enabled: true

---
#开发环境
spring:
  config:
    activate:
      on-profile: sit
springdoc:
  api-docs:
    enabled: true
---
#本地环境
spring:
  config:
    activate:
      on-profile: uat
springdoc:
  api-docs:
    enabled: true

---
#生产环境
spring:
  config:
    activate:
      on-profile: prd
springdoc:
  api-docs:
    enabled: false