package org.dows.hep.api.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;
import org.dows.framework.api.StatusCode;

/**
 * @author runsix
 */
@Getter
@AllArgsConstructor
/* runsix:ESC = ExceptionStatusCode */
public enum EnumESC implements StatusCode {
    VALIDATE_EXCEPTION(40000, "参数不正确"),
    INDICATOR_CATEGORY_DELETE_FAILED(50101, "指标类别删除失败"),
    SYSTEM_BUSY_PLEASE_OPERATOR_INDICATOR_CATEGORY_LATER(50102, "系统繁忙，请稍后重新操作指标类别"),
    INDICATOR_CATEGORY_HAS_DATA_CANNOT_DELETE(50103, "该类别下有数据，不能删除"),
    SYSTEM_BUSY_PLEASE_OPERATOR_INDICATOR_INSTANCE_LATER(50104, "系统繁忙，请稍后重新操作指标类别"),
    SYSTEM_BUSY_PLEASE_OPERATOR_INDICATOR_FUNC_LATER(50105, "系统繁忙，请稍后重新操作指标功能"),
    SYSTEM_BUSY_PLEASE_OPERATOR_INDICATOR_VIEW_BASE_INFO_LATER(50106, "系统繁忙，请稍后重新操作查看指标基本信息"),
    SYSTEM_BUSY_PLEASE_OPERATOR_INDICATOR_VIEW_MONITOR_FOLLOWUP_LATER(50107, "系统繁忙，请稍后重新操作查看指标监测随访"),
    SYSTEM_INDICATOR_INSTANCE_CANNOT_DELETE(50108, "系统自带指标，不允许删除"),
    SYSTEM_INDICATOR_CATEGORY_CANNOT_DELETE(50109, "系统自带目录，不允许删除"),
    RS_CALCULATE_ERROR(50110, "计算出错，请及时联系管理员"),
    INDICATOR_EXPRESSION_ID_IS_ILLEGAL(50111,  "公式id不合法"),
    INDICATOR_EXPRESSION_CIRCLE_DEPENDENCY(50112, "指标管理公式不允许循环依赖"),
    INDICATOR_EXPRESSION_MIN_MAX_MUST_BE_DIGIT(50113, "指标管理公式上下限只能是数字"),
    INDICATOR_EXPRESSION_MAX_MUST_GE_MIN(50114, "指标管理公式上下限，如果最大最小值都存在，最大值必须大于等于最小值"),
    INDICATOR_EXPRESSION_ITEM_ID_IS_ILLEGAL(50115,  "公式细项id不合法"),

    INDICATOR_EXPRESSION_CHECK_INDICATOR_INSTANCE_ID_DOES_NOT_EXIST(50116, "检查公式对应指标不存在"),
    INDICATOR_EXPRESSION_CHECK_CONDITION_MUST_BE_TRUE_OR_FALSE(50117, "检查公式的条件必须为true或false"),
    DATABASE_INDICATOR_MANAGEMENT_RESULT_CANNOT_BE_BLANK(50118, "数据库指标管理的公式结果不能为空"),
    DATABASE_INDICATOR_JUDGE_RISK_FACTOR_RESULT_ONLY_CAN_BE_BLANK(50119, "数据库危险因素的公式是一个条件，结果不允许有值"),
    DATABASE_LABEL_MANAGEMENT_FACTOR_RESULT_ONLY_CAN_BE_BLANK(50120, "数据库标签管理的公式是一个条件，结果不允许有值"),
    DATABASE_CROWDS_FACTOR_RESULT_ONLY_CAN_BE_BLANK(50121, "数据库人群类型的公式是一个条件，结果不允许有值"),
    DATABASE_RISK_MODEL_RESULT_CANNOT_BE_BLANK(50122, "数据库指标管理的公式结果不能为空"),
    CASE_INDICATOR_INSTANCE_ID_IS_ILLEGAL(50123, "案例指标id对应的案例指标不存在"),
    CASE_INDICATOR_INSTANCE_COME_FROM_DATABASE_CANNOT_DELETE(50124, "该案例指标来自数据库，不允许删除"),
    SYSTEM_BUSY_PLEASE_OPERATOR_CASE_INDICATOR_INSTANCE_LATER(50125, "系统繁忙，请稍后重新操作案例指标"),
    CASE_INDICATOR_INSTANCE_ID_CATEGORY_REF_IS_ILLEGAL(50126, "案例指标id对应的目录关联关系不存在"),
    CASE_INDICATOR_INSTANCE_ID_RULE_IS_ILLEGAL(50127, "案例指标id对应的规则不存在"),
    DELETE_INDICATOR_INSTANCE_FAILED_INDICATOR_VIEW_BASE_INFO_DESCR_REF_ENTITY(50128, "删除指标失败，存在于查看指标-基本信息-指标描述表"),
    DELETE_INDICATOR_INSTANCE_FAILED_INDICATOR_VIEW_BASE_INFO_MONITOR_CONTENT_REF_ENTITY(50129, "删除指标失败，存在于查看指标-基本信息-指标监测表"),
    DELETE_INDICATOR_INSTANCE_FAILED_INDICATOR_VIEW_BASE_INFO_SINGLE_ENTITY(50130, "删除指标失败，存在于查看指标-基本信息-单一指标"),
    DELETE_INDICATOR_INSTANCE_FAILED_INDICATOR_VIEW_MONITOR_CONTENT_REF_ENTITY(50131, "删除指标失败，存在于查看指标-指标随访表"),
    DELETE_INDICATOR_INSTANCE_FAILED_INDICATOR_VIEW_PHYSICAL_EXAM_ENTITY(50132, "删除指标失败，存在于查看指标-二级类-无报告"),
    DELETE_INDICATOR_INSTANCE_FAILED_INDICATOR_VIEW_SUPPORT_EXAM_ENTITY(50133, "删除指标失败，存在于查看指标-四级类-无报告"),
    DELETE_INDICATOR_INSTANCE_FAILED_INDICATOR_EXPRESSION_ENTITY(50134, "删除指标失败，存在于指标公式接收主体中"),
    DELETE_INDICATOR_INSTANCE_FAILED_INDICATOR_EXPRESSION_INFLUENCE_ENTITY(50135, "删除指标失败，存在于指标公式中"),
    INDICATOR_CATEGORY_ID_IS_ILLEGAL(50136, "目录id对应的目录不存在"),
    DELETE_INDICATOR_CATEGORY_FAILED_INDICATOR_VIEW_MONITOR_FOLLOWUP_ENTITY(50137, "删除目录失败，此目录下存在监测随访"),
    DELETE_INDICATOR_CATEGORY_FAILED_INDICATOR_VIEW_PHYSICAL_EXAM_ENTITY(50138, "删除目录失败，此目录下存在查看指标-二级类-无报告"),
    DELETE_INDICATOR_CATEGORY_FAILED_INDICATOR_VIEW_SUPPORT_EXAM_ENTITY(50139, "删除目录失败，此目录下存在查看指标-四级类-无报告"),
    DELETE_INDICATOR_CATEGORY_FAILED_INDICATOR_JUDGE_RISK_FACTOR_ENTITY(50140, "删除目录失败，此目录下存在判断操作-二级类-无报告"),
    DELETE_INDICATOR_CATEGORY_FAILED_INDICATOR_JUDGE_HEALTH_GUIDANCE_ENTITY(50141, "删除目录失败，此目录下存在判断操作-二级类-有报告"),
    DELETE_INDICATOR_CATEGORY_FAILED_INDICATOR_JUDGE_HEALTH_PROBLEM_ENTITY(50142, "删除目录失败，此目录下存在判断操作-三级类-无报告"),
    DELETE_INDICATOR_CATEGORY_FAILED_TAG_INSTANCE_ENTITY(50143, "删除目录失败，此目录下存在标签"),
    DELETE_CROWDS_FAILED_RISK_MODEL_ENTITY(50144, "删除人群类别失败，此人群类别下存在死亡原因"),
    ;
    private final Integer code;
    private final String descr;
}
