upload:
  dev:
    cgp:
      host: '192.168.1.60'
      port: 9031
      path: '/v1/anonymous/file/upload'
    hep:
      host: '192.168.1.60'
      port: 10001
      path: '/v1/anonymous/file/upload'
  sit:
    cgp:
      host: '192.168.1.60'
      port: 9031
      path: '/v1/anonymous/file/upload'
    hep:
      host: '192.168.1.60'
      port: 20001
      path: '/v1/anonymous/file/upload'
  uat:
    cgp:
      host: '192.168.1.60'
      port: 9031
      path: '/v1/anonymous/file/upload'
    hep:
      host: '192.168.1.60'
      port: 30001
      path: '/v1/anonymous/file/upload'
  prd:
    cgp:
      host: '192.168.1.60'
      port: 9031
      path: '/v1/anonymous/file/upload'
    hep:
      host: '192.168.1.60'
      port: 40001
      path: '/v1/anonymous/file/upload'

  hb:
    cgp:
      host: '192.168.1.60'
      port: 9031
      path: '/v1/anonymous/file/upload'
    hep:
      host: '192.168.1.119'
      port: 9001
      path: '/v1/anonymous/file/upload'

pdf:
  cgp:
    headerTemplate: '<div
      style="width: calc(100% - 28px); margin-top: -13px; font-size:8px;border-bottom:2px solid #e1dafb;padding:6px 14px;display: flex; justify-content: space-between; align-items:center;">
      <span style="color: #9a7ff7; font-size: 12px; font-family: my-font;">页首</span>
      </div>'
    footerTemplate: '<div
      style="width:calc(100% - 28px);margin-bottom: -20px; font-size:8px; padding:15px 14px;display: flex; justify-content: space-between; ">
      <span style="color: #9a7ff7; font-size: 10px;">页尾</span>
      <span style="color: #9a7ff7; font-size: 13px;" class="pageNumber"></span>
      </div>'
  hep:
    headerTemplate: '<div
      style="width: calc(100% - 28px); margin-top: -13px; font-size:8px;border-bottom:2px solid #e1dafb;padding:6px 14px;display: flex; justify-content: space-between; align-items:center;">
      <span style="color: #9a7ff7; font-size: 12px; font-family: my-font;">页首</span>
      </div>'
    footerTemplate: '<div
      style="width:calc(100% - 28px);margin-bottom: -20px; font-size:8px; padding:15px 14px;display: flex; justify-content: space-between; ">
      <span style="color: #9a7ff7; font-size: 10px;">页尾</span>
      <span style="color: #9a7ff7; font-size: 13px;" class="pageNumber"></span>
      </div>'

