FROM eclipse-temurin:17-jre as builder

WORKDIR application
ARG JAR_FILE=./target/*.jar
COPY ${JAR_FILE} app.jar

RUN java -Djarmode=layertools -jar app.jar extract && rm app.jar


FROM eclipse-temurin:17-jre

ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
ENV JAVA_OPTS="-Xms128m -Xmx256m"

ENV SPRING_PROFILE="-Dspring.profiles.active=dev"
#配置开启debug
ENV JAVA_DEBUG="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8040"

WORKDIR application
COPY --from=builder application/dependencies/ ./
COPY --from=builder application/spring-boot-loader/ ./
COPY --from=builder application/snapshot-dependencies/ ./
COPY --from=builder application/application/ ./

EXPOSE 8080

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS $JAVA_DEBUG $SPRING_PROFILE org.springframework.boot.loader.JarLauncher"]




#FROM eclipse-temurin:17-jre
#ARG JAR_FILE
#COPY hep-app/target/${JAR_FILE} /root/${JAR_FILE}
#RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
#RUN echo "Asia/Shanghai" > /etc/timezone
#ENV JAVA_OPTS='-Xmx2048m -Xms2048m'
#ENV JAR_LOCATION=/root/$JAR_FILE
#
#CMD java $JAVA_OPTS -Dspring.profiles.active=dev -jar $JAR_LOCATION