FROM eclipse-temurin:17-jre
ARG JAR_FILE
COPY hep-app/target/${JAR_FILE} /root/${JAR_FILE}
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo "Asia/Shanghai" > /etc/timezone
ENV JAVA_OPTS='-Xmx2048m -Xms2048m'
ENV JAR_LOCATION=/root/$JAR_FILE

#CMD java $JAVA_OPTS -Dspring.profiles.active=dev -jar $JAR_LOCATION
ENV SPRING_PROFILE="-Dspring.profiles.active=dev"
#配置开启debug
ENV JAVA_DEBUG="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8040"
ENTRYPOINT ["java","$JAVA_OPTS","$JAVA_DEBUG","$SPRING_PROFILE","-jar","$JAR_LOCATION"]