version: '3'
services:
  elasticsearch842-prd:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.2
    container_name: elasticsearch842-prd
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - node.name=elasticsearch
      - cluster.name=elasticsearch
      - discovery.type=single-node

      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false

      - ingest.geoip.downloader.enabled=false

      - ES_JAVA_OPTS=-Xms3g -Xmx3g
      - TZ=Asia/Shanghai
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./elasticsearch/conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  #      - ./elasticsearch/data:/usr/share/elasticsearch/data
  #      - ./elasticsearch/logs/elasticsearch.log:/usr/share/elasticsearch/logs/elasticsearch.log
networks:
  default:
    external:
      name: prd_net