version: "3"
services:
  nginx-prd:
    image: nginx
    restart: unless-stopped
    container_name: nginx-prd
    ports:
      - 480:80
    volumes:
      - ./nginx/conf:/etc/nginx
      - ./nginx/cert/:/etc/cert/                   # ssl证书
      - ./nginx/www/:/usr/share/nginx/html/         # 默认显示的index网页
      - ./nginx/logs/:/var/log/nginx/               # 日志文件

networks:
  default:
    external:
      name: prd_net