
---
#生产环境
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      #uri: mongodb://192.168.1.60:17017
      username: test
      password: "123456"
      database: user
      port: 17017
      host: 192.168.1.60
      #collection-name: user
      authentication-database: user
#      repositories:
#        enabled: true



---
#测试环境
spring:
  config:
    activate:
      on-profile: sit
  data:
    mongodb:
      uri: mongodb://admin:123456@192.168.1.60:27017/hep

---
#开发环境
spring:
  config:
    activate:
      on-profile: uat
  data:
    mongodb:
      uri: mongodb://admin:123456@192.168.1.60:37017/hep
---
#本地环境
spring:
  config:
    activate:
      on-profile: prd
  data:
    mongodb:
      uri: mongodb://admin:123456@192.168.1.60:47017/hep