findsoft:
  name: 健康管理情景模拟沙盘对抗比赛平台
  version: 3.2.0
  copy-right: © 2023 findsoft 上海哲寻信息科技有限公司
  abbreviation: 健康管理
  score-audit: true
  findsoftLogo: pdf/images/findsoft-logo.jpg
  cover: pdf/images/cover.png
  logo: pdf/images/logo.png
  exptOverviewReportTitle: 健康管理实验总报告
  exptSchemeReportTitle: 健康管理方案设计比赛平台
  exptSandReportTitle: 健康管理情景模拟沙盘对抗比赛平台
  exptOverviewFtl: experiment-overview.ftl
  exptSchemeFtl: experiment-scheme.ftl
  exptSandFtl: experiment-sand.ftl