findsoft:
  name: 健康管理情景模拟沙盘对抗比赛平台
  version: 3.2.0
  copy-right: © 2023 findsoft 上海哲寻信息科技有限公司
  abbreviation: 健康管理
  score-audit: true
  pdf-overview-title: 健康管理情景模拟沙盘对抗比赛平台
  pdf-plan-title: 健康管理情景模拟沙盘对抗比赛平台
  open-knowledge-tool-menu: true