
---
#生产环境
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      host: 192.168.1.60
      port: 17017
      database: hep
      username: admin
      password: "123456"
      auth-source: admin
      authentication-database: hep
      #collection-name: user
      #auth-method: SCRAM-SHA-1



---
#测试环境
spring:
  config:
    activate:
      on-profile: sit
  data:
    mongodb:
      username: admin
      password: "123456"
      database: hep
      port: 27017
      host: 192.168.1.60

---
#开发环境
spring:
  config:
    activate:
      on-profile: uat
  data:
    mongodb:
      username: admin
      password: "123456"
      database: hep
      port: 37017
      host: 192.168.1.60
---
#本地环境
spring:
  config:
    activate:
      on-profile: prd
  data:
    mongodb:
      username: admin
      password: "123456"
      database: hep
      port: 47017
      host: 192.168.1.60