---
spring:
  config:
    activate:
      on-profile: dev

  data:
    redis:
      database: 0
      host: 192.168.1.60
      port: 16379
      password:
      #配置jedis客户端，这里也可以jedis替换为lettuce客户端，下级配置都一样
      jedis:
        pool:
          # 连接池中的最大空闲连接 默认8
          max-idle: 8
          # 连接池中的最小空闲连接 默认0
          min-idle: 0
          # 连接池最大连接数 默认8 ，负数表示没有限制
          max-active: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
          max-wait: -1
      timeout: 3000
  cache:
    type: redis
    #当自定义ChacheManager时，就这里的配置不需要配置，配置了也不起作用
    # redis:
    #   use-key-prefix: true
    #  key-prefix: "hep:"
    #  time-to-live: 60000  #缓存超时时间 单位：ms
    #  cache-null-values: false #是否缓存空值
    cache-names:
      - "experiment:indicator:"


#cache:
#  #自定义某些缓存空间的过期时间
#  ttl: '{"user":60,"dept":30}'


---
spring:
  config:
    activate:
      on-profile: sit
  data:
    redis:
      database: 0
      host: 192.168.1.60
      port: 26379
      password:
      #配置jedis客户端，这里也可以jedis替换为lettuce客户端，下级配置都一样
      jedis:
        pool:
          # 连接池中的最大空闲连接 默认8
          max-idle: 8
          # 连接池中的最小空闲连接 默认0
          min-idle: 0
          # 连接池最大连接数 默认8 ，负数表示没有限制
          max-active: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
          max-wait: -1
      timeout: 3000
  cache:
    type: redis
    #当自定义ChacheManager时，就这里的配置不需要配置，配置了也不起作用
    # redis:
    #   use-key-prefix: true
    #  key-prefix: "hep:"
    #  time-to-live: 60000  #缓存超时时间 单位：ms
    #  cache-null-values: false #是否缓存空值
    cache-names:
      - "experiment:indicator:"

#cache:
#  #自定义某些缓存空间的过期时间
#  ttl: '{"user":60,"dept":30}'



---
#生产环境
spring:
  config:
    activate:
      on-profile: uat
  data:
    redis:
      database: 0
      host: 192.168.1.60
      port: 36379
      password:
      #配置jedis客户端，这里也可以jedis替换为lettuce客户端，下级配置都一样
      jedis:
        pool:
          # 连接池中的最大空闲连接 默认8
          max-idle: 8
          # 连接池中的最小空闲连接 默认0
          min-idle: 0
          # 连接池最大连接数 默认8 ，负数表示没有限制
          max-active: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
          max-wait: -1
      timeout: 3000
  cache:
    type: redis
    # 当自定义ChacheManager时，就这里的配置不需要配置，配置了也不起作用
    # redis:
    #   use-key-prefix: true
    #  key-prefix: "hep:"
    #  time-to-live: 60000  #缓存超时时间 单位：ms
    #  cache-null-values: false #是否缓存空值
    cache-names:
      - "experiment:indicator:"

#cache:
#  #自定义某些缓存空间的过期时间
#  ttl: '{"user":60,"dept":30}'



---
#生产环境
spring:
  config:
    activate:
      on-profile: prd
  data:
    redis:
      database: 0
      host: redis-paas-prd
      port: 46379
      password:
      #配置jedis客户端，这里也可以jedis替换为lettuce客户端，下级配置都一样
      jedis:
        pool:
          # 连接池中的最大空闲连接 默认8
          max-idle: 8
          # 连接池中的最小空闲连接 默认0
          min-idle: 0
          # 连接池最大连接数 默认8 ，负数表示没有限制
          max-active: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
          max-wait: -1
      timeout: 3000

  cache:
    type: redis
    # 当自定义ChacheManager时，就这里的配置不需要配置，配置了也不起作用
    # redis:
    #   use-key-prefix: true
    #  key-prefix: "hep:"
    #  time-to-live: 60000  #缓存超时时间 单位：ms
    #  cache-null-values: false #是否缓存空值
    #可以自定义多个
    cache-names:
      - "experiment:indicator:"

#cache:
#  #自定义某些缓存空间的过期时间
#  ttl: '{"user":60,"dept":30}'