management:
    endpoints:
        web:
            exposure:
                include: '*'

server:
    port: 9001
    undertow:
        buffer-size: 1024
        direct-buffers: true
        threads:
            io: 4
            worker: 32
#    servlet:
#        context-path: /hep1
soft:
    info:
        anonymous-paths: /login;/doc;/swagger;/api-docs;/hepapi;/report;


spring:
    application:
        name: dows-hep
    profiles:
        include: hep-mysql,hep-mybatis,hep-mvc,hep-oss,hep-apidoc,hep-redisson,hep-findsoft,hep-websocket,hep-cache,hep-mongodb,hep-pdf
        active: dev

    jackson:
        default-property-inclusion: always
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+08:00
        serialization:
          write-dates-as-timestamps: false


