oss:
  local:
    enable: true
    ossConfig:
      volumed:
        basePath: /data/resources/images/hep
        slice-config:
          task-num: 8
          part-size: 104857600

spring:
  servlet:
    multipart:
      # 根据实际需求作调整
      # 默认最大上传文件大小为1M，单个文件大小
      max-file-size: 10MB
      # 默认最大请求大小为10M，总上传的数据大小
      max-request-size: 15MB

## windows
#oss.local.enable = true
#oss.local.ossConfig.volumnd.basePath = d:/images
#oss.local.ossConfig.volumnd.slice-config.task-num = 8
#oss.local.ossConfig.volumnd.slice-config.part-size = 104857600
#spring.mvc.static-path-pattern=/**
#spring.resources.static-locations=file:D