---
#开发环境
spring:
  config:
    activate:
      on-profile: dev
pdf-server:
  server-url: http://192.168.1.60:8801/pdf
  app-code: hep
  env: dev
  scheme-expt-view-url: http://192.168.1.60:1801/report_view/group/
  scheme-group-view-url: http://192.168.1.60:1801/report_view/group/
  sand-expt-view-url: http://192.168.1.60:1801/report_view/group/
  sand-group-view-url: http://192.168.1.60:1801/report_view/group/
---
#测试环境
spring:
  config:
    activate:
      on-profile: test
pdf-server:
  server-url: http://192.168.1.60:8001/pdf
  app-code: hep
  env: sit
  scheme-expt-view-url: http://192.168.1.60:1801/report_view/group/
  scheme-group-view-url: http://192.168.1.60:1801/report_view/group/
  sand-expt-view-url: http://192.168.1.60:1801/report_view/group/
  sand-group-view-url: http://192.168.1.60:1801/report_view/group/
---
#预发布环境
spring:
  config:
    activate:
      on-profile: staging
pdf-server:
  server-url: http://192.168.1.60:8001/pdf
  app-code: hep
  env: uat
  scheme-expt-view-url: http://192.168.1.60:1801/report_view/group/
  scheme-group-view-url: http://192.168.1.60:1801/report_view/group/
  sand-expt-view-url: http://192.168.1.60:1801/report_view/group/
  sand-group-view-url: http://192.168.1.60:1801/report_view/group/
---
#产品环境
spring:
  config:
    activate:
      on-profile: prd
pdf-server:
  server-url: http://192.168.1.60:8001/pdf
  app-code: hep
  env: prd
  scheme-expt-view-url: http://192.168.1.60:1801/report_view/group/
  scheme-group-view-url: http://192.168.1.60:1801/report_view/group/
  sand-expt-view-url: http://192.168.1.60:1801/report_view/group/
  sand-group-view-url: http://192.168.1.60:1801/report_view/group/